### ISSUE TITLE
CartPole-v0 model can't be loaded by enjoy.py

### ISSUE THREAD

**Issue by swenner** [ikostrikov/pytorch-a2c-ppo-acktr-gail#148]
Baselines Version: 0.1.5
python3 main.py --env-name "CartPole-v0" --num-frames 100000

python3 enjoy.py --load-dir trained_models/a2c --env-name "CartPole-v0"
<pre>
Traceback (most recent call last):
  File "enjoy.py", line 66, in <module>
    obs, reward, done, _ = env.step(action)
  File "/home/simon/.local/lib/python3.5/site-packages/baselines/common/vec_env/__init__.py", line 78, in step
    return self.step_wait()
  File "/home/simon/pytorch-a2c-ppo-acktr-git/envs.py", line 145, in step_wait
    obs, reward, done, info = self.venv.step_wait()
  File "/home/simon/.local/lib/python3.5/site-packages/baselines/common/vec_env/vec_normalize.py", line 26, in step_wait
    obs, rews, news, infos = self.venv.step_wait()
  File "/home/simon/.local/lib/python3.5/site-packages/baselines/common/vec_env/dummy_vec_env.py", line 23, in step_wait
    obs_tuple, self.buf_rews[i], self.buf_dones[i], self.buf_infos[i] = self.envs[i].step(self.actions[i])
  File "/home/simon/.local/lib/python3.5/site-packages/gym/wrappers/time_limit.py", line 31, in step
    observation, reward, done, info = self.env.step(action)
  File "/home/simon/.local/lib/python3.5/site-packages/gym/envs/classic_control/cartpole.py", line 92, in step
    assert self.action_space.contains(action), "%r (%s) invalid"%(action, type(action))
AssertionError: array([0, 0]) (<class 'numpy.ndarray'>) invalid
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7f2a294b8d08>
Traceback (most recent call last):
  File "/usr/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
</pre>

**Comment by ikostrikov** [comment]
Thanks for reporting the problem!

Fixed in https://github.com/ikostrikov/pytorch-a2c-ppo-acktr-gail/commit/88080da828dd4132bec0456b996e516fe356f75f
