### ISSUE TITLE
Env Observation space dimension error whenever I try to train any model

### ISSUE THREAD

**Issue by ashwinipokle** [ikostrikov/pytorch-a2c-ppo-acktr-gail#191]
Hello,

I followed steps mentioned [here](https://github.com/ikostrikov/pytorch-a2c-ppo-acktr-gail#requirements) to install requirements for this repository. There is one minor change, I am using virtualenv instead of conda to install pytorch. I wanted to test my installation and I tried to train model using the commands mentioned in [this](https://github.com/ikostrikov/pytorch-a2c-ppo-acktr-gail#training) section. I am unable to get any model to train. Everytime I get the following error.

Traceback (most recent call last):
  File "main.py", line 14, in <module>
    from a2c_ppo_acktr import algo, utils
  File "/home/admin/ppo_mm/pytorch-a2c-ppo-acktr-gail/a2c_ppo_acktr/algo/__init__.py", line 1, in <module>
    from .a2c_acktr import A2C_ACKTR
  File "/home/admin/ppo_mm/pytorch-a2c-ppo-acktr-gail/a2c_ppo_acktr/algo/a2c_acktr.py", line 5, in <module>
    from a2c_ppo_acktr.algo.kfac import KFACOptimizer
  File "/home/admin/ppo_mm/pytorch-a2c-ppo-acktr-gail/a2c_ppo_acktr/algo/kfac.py", line 8, in <module>
    from a2c_ppo_acktr.utils import AddBias
  File "/home/admin/ppo_mm/pytorch-a2c-ppo-acktr-gail/a2c_ppo_acktr/utils.py", line 7, in <module>
    from a2c_ppo_acktr.envs import VecNormalize
  File "/home/admin/ppo_mm/pytorch-a2c-ppo-acktr-gail/a2c_ppo_acktr/envs.py", line 146
    assert len(op) == 3, f"Error: Operation, {str(op)}, must be dim3"

**Comment by ashwinipokle** [comment]
Quick update: I followed installation instruction in anaconda environment and I still get a similar error whenever I try to train model.
Traceback (most recent call last):
  File "main.py", line 166, in <module>
    main()
  File "main.py", line 46, in main
    base_kwargs={'recurrent': args.recurrent_policy})
  File "/home/admin/ppo_mm/pytorch-a2c-ppo-acktr-gail/a2c_ppo_acktr/model.py", line 21, in __init__
    if len(obs_shape) == 3:
TypeError: object of type 'NoneType' has no len()

Seems like this is an issue with the version of OpenAI gym being used. Could you please let me know which version of OpenAI gym is compatible with the codebase ?

**Comment by YuiiCh** [comment]
me too

**Comment by ikostrikov** [comment]
It seems to work for me. Could you check whether you install the latest versions of gym and baselines?

I ran
```bash
 python main.py --env-name "PongNoFrameskip-v4"
```

**Comment by enikhu** [comment]
Tried with latest versions of gym and baseline. The issue still remains. Any ideas here ?

**Comment by YuiiCh** [comment]
Thank you, now it works~

发件人: Nikhil Agarwal
发送时间: 2019年6月12日 3:20
收件人: ikostrikov/pytorch-a2c-ppo-acktr-gail
抄送: YuiiCh; Comment
主题: Re: [ikostrikov/pytorch-a2c-ppo-acktr-gail] Env Observation spacedimension error whenever I try to train any model (#191)

Tried with latest versions of gym and baseline. The issue still remains. Any ideas here ?

**Comment by rebellojason7** [comment]
you have to remove the 'f' from the statement 
assert len(op) == 3, f"Error: Operation, {str(op)}, must be dim3"

change to 
assert len(op) == 3, "Error: Operation, {str(op)}, must be dim3"

**Comment by henrycharlesworth** [comment]
For me it was because I was using Python 3.5, once I updated to 3.6 it was working (I was getting a very similar error, not exactly the same: pytorch-a2c-ppo-acktr-gail/a2c_ppo_acktr/envs.py", line 146
    assert len(op) == 3, f"Error: Operation, {str(op)}, must be dim3")

Looking at the code there:

super(TransposeImage, self).__init__(env)
assert len(op) == 3, f"Error: Operation, {str(op)}, must be dim3"

It's using an f-string which is only supported in >=Python 3.6. So I think this means that this code won't work in Python 3.5 (which is annoying, as I can only get mujoco-py to run in python 3.5... but that's a whole different issue!). It might be worth mentioning this somewhere!
