### ISSUE TITLE
error happened when running with ppo

### ISSUE THREAD

**Issue by tangypnuaa** [ikostrikov/pytorch-a2c-ppo-acktr-gail#201]
env--reacher
algo--ppo
error:

Traceback (most recent call last):
  File "/home/al/Desktop/pytorch-a2c-ppo-acktr-gail-master/main.py", line 196, in <module>
    main()
  File "/home/al/Desktop/pytorch-a2c-ppo-acktr-gail-master/main.py", line 42, in main
    args.gamma, args.log_dir, device, False)
  File "/home/al/Desktop/pytorch-a2c-ppo-acktr-gail-master/a2c_ppo_acktr/envs.py", line 91, in make_vec_envs
    envs = ShmemVecEnv(envs, context='fork')
  File "/home/al/Desktop/pytorch-a2c-ppo-acktr-gail-master/baselines/common/vec_env/shmem_vec_env.py", line 44, in __init__
    for _ in env_fns]
  File "/home/al/Desktop/pytorch-a2c-ppo-acktr-gail-master/baselines/common/vec_env/shmem_vec_env.py", line 44, in <listcomp>
    for _ in env_fns]
  File "/home/al/Desktop/pytorch-a2c-ppo-acktr-gail-master/baselines/common/vec_env/shmem_vec_env.py", line 43, in <dictcomp>
    {k: ctx.Array(_NP_TO_CT[self.obs_dtypes[k].type], int(np.prod(self.obs_shapes[k]))) for k in self.obs_keys}
KeyError: <class 'numpy.float64'>

**Comment by dmitrySorokin** [comment]
I got the same error

**Comment by ikostrikov** [comment]
Works on my linux machine. Can you provide more details?

**Comment by JulianoLagana** [comment]
I get the same error.

**Comment by dmitrySorokin** [comment]
Ubuntu 18.04
I am using latest commit from baselines (https://github.com/openai/baselines/commit/c57528573ea695b19cd03e98dae48f0082fb2b5e)

I seems like a problem with ShmemVecEnv. 
Switching to SubprocVecEnv helped me.

**Comment by ikostrikov** [comment]
Great! Can you submit a PR with the fix?

**Comment by JulianoLagana** [comment]
After some investigation I now think that the culprit of this is actually the baselines repo: [`ShmemVecEnv` does not support float64 type yet](https://github.com/openai/baselines/issues/749). While we wait for them to fix this, one can either use `SubprocVecEnv` (which can be considerably slower), or try my workaround as described [here](https://github.com/openai/baselines/issues/749#issuecomment-518234997).
