### ISSUE TITLE
ShmemVecEnv not found

### ISSUE THREAD

**Issue by NILOIDE** [ikostrikov/pytorch-a2c-ppo-acktr-gail#228]
Hi,

I installed baselines through pip. However, the file shmem_vec_env.py is not present in 0.1.5. Version 0.1.5 appears to be the latest version of baselines in pip, and version 0.1.4 seems to be much too old (causes a lot more dependencies to be missing). Trying to main.py causes the import `from baselines.common.vec_env.shmem_vec_env import ShmemVecEnv
` in envs.py to bring up an error. 

What is odd is that I can go to the official baselines [https://github.com/openai/baselines/blob/master/baselines/common/vec_env/shmem_vec_env.py](GitHub page) which shows the file in the intended location.

Am I not installing the baselines package correctly? Is there a nicer way to get the project to run without manually copy-pasting the shmem_vec_env.py file from the official baselines repo into my conda environment?

**Comment by ikostrikov** [comment]
Hi,

Please install baselines by compiling from the source code as described in readme.

**Comment by NILOIDE** [comment]
Hi,

So I managed to install baselines from source, but now I have another issue.

Apparently, when initializing ShmemVecEnv, the context for 'fork' cannot be found. Here is the full terminal output.

`Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Program Files\JetBrains\PyCharm Community Edition with Anaconda plugin 2019.2.3\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition with Anaconda plugin 2019.2.3\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/nilst/Documents/Adversarial_curiosity/code/test_ppo.py", line 150, in <module>
    main()
  File "C:/Users/nilst/Documents/Adversarial_curiosity/code/test_ppo.py", line 41, in main
    args.gamma, args.log_dir, device, False)
  File "C:\Users\nilst\Documents\Adversarial_curiosity\code\modules\algorithms\PPO\envs.py", line 90, in make_vec_envs
    envs = ShmemVecEnv(envs, context='fork')
  File "C:\Users\nilst\.conda\envs\AC\lib\site-packages\baselines\common\vec_env\shmem_vec_env.py", line 30, in __init__
    ctx = mp.get_context(context)
  File "C:\Users\nilst\.conda\envs\AC\lib\multiprocessing\context.py", line 238, in get_context
    return super().get_context(method)
  File "C:\Users\nilst\.conda\envs\AC\lib\multiprocessing\context.py", line 192, in get_context
    raise ValueError('cannot find context for %r' % method) from None
ValueError: cannot find context for 'fork'
`

I found a post online about a similar issue, where they say this might be due to how Windows does multiprocessing. If I remove the context (and use the default context ('spawn'), the issue goes away. I however do not understand what this context is meant to do. What is the context 'fork' meant to do? How does it defer from 'spawn' (which is the default?
