### ISSUE TITLE
assert 'NoFrameskip' in env.spec.id 

### ISSUE THREAD

**Issue by liuqi8827** [ikostrikov/pytorch-a2c-ppo-acktr-gail#253]
Thanks for your great work.

I'm facing a problem when I change the `evn-name`

I can run the PongNoFrameskip-v4 environment successfully by
`python main.py --env-name "PongNoFrameskip-v4" --algo ppo --use-gae --lr 2.5e-4 --clip-param 0.1 --value-loss-coef 0.5 --num-processes 8 --num-steps 128 --num-mini-batch 4 --log-interval 1 --use-linear-lr-decay --entropy-coef 0.01`

However, when I change the env-name to other name **(AirRaid-ram-v0, DemonAttack-ram-v0, DemonAttack-v0 ...)**, 
there is an error :
```
Traceback (most recent call last):
  File "/home/lq/pytorch-a2c-ppo-acktr-gail/main.py", line 240, in <module>
    main()
  File "/home/lq/pytorch-a2c-ppo-acktr-gail/main.py", line 68, in main
    args.gamma, args.log_dir, device, False)
  File "/home/lq/pytorch-a2c-ppo-acktr-gail/a2c_ppo_acktr/envs.py", line 89, in make_vec_envs
    envs = ShmemVecEnv(envs, context='fork')
  File "/home/lq/pytorch-a2c-ppo-acktr-gail/baselines/baselines/common/vec_env/shmem_vec_env.py", line 36, in __init__
    dummy = env_fns[0]()
  File "/home/lq/pytorch-a2c-ppo-acktr-gail/a2c_ppo_acktr/envs.py", line 43, in _thunk
    env = make_atari(env_id)
  File "/home/lq/pytorch-a2c-ppo-acktr-gail/baselines/baselines/common/atari_wrappers.py", line 268, in make_atari
    assert 'NoFrameskip' in env.spec.id
AssertionError
```

Can you give me some suggestions?
Thanks a lot!

**Comment by liuqi8827** [comment]
It works well.

**Comment by ikostrikov** [comment]
At the moment this repository doesn't support RAM observations.
