### ISSUE TITLE
enjoy.py failes. Unexpected argument 'ret'

### ISSUE THREAD

**Issue by jakefoster954** [ikostrikov/pytorch-a2c-ppo-acktr-gail#263]
This was run on the master branch. Help appreciated.

Traceback (most recent call last):
  File "enjoy.py", line 46, in <module>
    allow_early_resets=False)
  File "..../pytorch-a2c-ppo-acktr-gail/a2c_ppo_acktr/envs.py", line 99, in make_vec_envs
    envs = VecNormalize(envs, ret=False)
  File "..../pytorch-a2c-ppo-acktr-gail/a2c_ppo_acktr/envs.py", line 191, in __init__
    super(VecNormalize, self).__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'ret'

**Comment by ikostrikov** [comment]
Fixed in https://github.com/ikostrikov/pytorch-a2c-ppo-acktr-gail/commit/b03eba0158b59d0b2412e2844a68b9115508066a

Let me know if it fixes the issue.

**Comment by jakefoster954** [comment]
Yes, that fix worked.
